FROM docker.io/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ARG cmakeVersion

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y autoremove
RUN apt-get -y install --no-install-recommends \
    clang \
    curl \
    gawk \
    gcc \
    g++ \
    git \
    libbsd-dev \
    libbson-dev \
    libcurl4-openssl-dev \
    libmicrohttpd-dev \
    libmongoc-dev \
    libncurses-dev \
    libpmem-dev \
    liburcu-dev \
    libyaml-dev \
    maven \
    ninja-build \
    openjdk-8-jdk \
    pkg-config \
    python3-dev \
    python3-pip
RUN python3 -m pip install \
    Cython \
    meson==0.62.2
RUN mkdir -p /usr/local
RUN curl -sSLo /tmp/cmake.tar.gz \
    https://github.com/Kitware/CMake/releases/download/v${cmakeVersion}/cmake-${cmakeVersion}-linux-x86_64.tar.gz
RUN tar --strip-components 1 -xf /tmp/cmake.tar.gz --directory /usr/local
RUN rm /tmp/cmake.tar.gz
RUN ulimit -c unlimited
