FROM docker.io/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y autoremove
RUN apt-get -y install --no-install-recommends \
    clang \
    cmake \
    gawk \
    gcc \
    g++ \
    git \
    libbsd-dev \
    libbson-dev \
    libcurl4-openssl-dev \
    libmicrohttpd-dev \
    libmongoc-dev \
    libncurses-dev \
    liburcu-dev \
    libyaml-dev \
    maven \
    ninja-build \
    openjdk-8-jdk \
    pkg-config \
    python3-dev \
    python3-pip
RUN python3 -m pip install \
    Cython \
    meson==0.62.2
RUN ulimit -c unlimited
