name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.sh"
      - .github/workflows/shellcheck.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - name: Checkout ci-images
        uses: actions/checkout@v4

      - name: Initialize
        run: |
          dnf install -y findutils ShellCheck

      - name: Lint
        run: |
          ./scripts/shellcheck.sh
